### ISSUE TITLE
[Request] Comment section color in python

### ISSUE THREAD

**Issue by miguelcarax** [rodbor/fallout4-syntax#1]
¿Could be possible to set the same color of green for the 2 section? Thx

![image](https://cloud.githubusercontent.com/assets/9194709/12203677/89a9ea3c-b630-11e5-8a2e-b56ec18c9609.png)

**Comment by rodbor** [comment]
Hi,
It's done, you can download it again.

**Comment by miguelcarax** [comment]
Sorry but i wanted the darkest one (bottom) in the section on the top, sorry for misunderstanding :(

**Comment by rodbor** [comment]
Ah yes, I see it now. But I wanted from the beginning that the comments were in another tone of green.
Sorry about that.
